export const frases = [
    "Siga os bons e aprenda com eles.",
    "O bom-senso vale mais do que muito conhecimento.",
    "o riso é a maior distância entre duas pessoas.",
    "Deixe de lado as preocupações e seja feliz.",
    "Realize o óbvio, penser no improvavel e conquiste o impossivel.",
    "Acredite em milagres, mas não dependa deles.",
    "A maior barreira parea o sucesso é o medo do fracaso.",
    "Grandes mudanças estão a caminho, mas você está pronto para elas.",
    "Um amigo distante trará notícias interessantes em breve.",
    "Sua criatividade será a chave para desbloquear novas oportunidades.",
    "Seja gentil com os outros e a bondade voltará para você em dobro.",
    "Uma surpresa agradável espera por você em um futuro próximo.",
    "Aproveite as pequenas coisas da vida e encontre alegria na simplicidade.",
    "Seja corajoso e assuma riscos, pois isso o levará a grandes recompensas.",
    "Sua paixão e dedicação irão levar você longe em sua carreira.",
    "Aprenda com seus erros e use essas lições para alcançar o sucesso.",
    "Não se preocupe com o que os outros pensam de você, siga seu próprio caminho.",
    "Aprenda a deixar ir o passado e abrace o presente.",
    "A gratidão é a chave para encontrar a felicidade verdadeira.",
    "Faça o que você ama e o dinheiro seguirá.",
    "Mantenha-se fiel a si mesmo e não comprometa seus valores.",
    "Novas oportunidades surgirão se você se abrir para elas.",
    "Acredite em si mesmo e nos seus sonhos, e eles se tornarão realidade.",
    "Um novo amor está a caminho para iluminar sua vida.",
    "A vida é curta, aproveite cada momento.",
    "A sorte favorece os ousados.",
    "Tudo o que você precisa para alcançar seus objetivos já está dentro de você.",
    "Boas notícias estão a caminho, prepare-se para comemorar!",
    "Seja paciente e confie no processo, o resultado final será gratificante.",
    "O amor está ao seu redor, abra seus olhos e seu coração.",
    "Aproveite o momento presente e deixe suas preocupações para trás.",
    "Mantenha a mente aberta para novas ideias e possibilidades.",
    "A jornada pode ser difícil, mas a recompensa valerá a pena.",
    "A verdadeira felicidade é encontrada na conexão com os outros.",
    "Faça escolhas sábias e viva com alegria e integridade.",
    "Aprenda a ouvir sua intuição, ela o guiará no caminho certo.",
    "Mantenha a mente positiva e atraia coisas positivas para sua vida.",
    "O sucesso vem para aqueles que trabalham duro e nunca desistem.",
    "A vida é uma aventura, aproveite-a ao máximo.",
    "Cultive a gratidão e sua vida será preenchida com bênçãos.",
    "Aprenda a perdoar a si mesmo e aos outros para encontrar a paz interior.",
    "A mudança é inevitável, abrace-a e aproveite a jornada.",
    "A sorte está do seu lado hoje, use-a sabiamente.",
    "Seja corajoso o suficiente para seguir seu coração e suas paixões.",
    "Não tenha medo de pedir ajuda quando precisar, todos precisamos de apoio às vezes.",
    "Seja gentil, pois suas palavras e ações têm um grande impacto nos outros.",
    "Nunca desista de seus sonhos, você é capaz de alcançar tudo o que deseja.",
    "Seja o tipo de pessoa que você gostaria de ter por perto.",
    "Mantenha-se fiel a si mesmo e não mude por ninguém.",
    "Aja com bondade e amor em seu coração e você sempre encontrará a felicidade.",
    "Seja grato por suas bênçãos e elas se multiplicarão.",
    "Acredite em si mesmo e em suas habilidades, você é mais capaz do que imagina.",
    "Aproveite as pequenas coisas da vida e seja grato por elas.",
    "Aprenda a deixar ir o que não lhe serve mais e abra espaço para o novo.",
    "A vida é curta, viva-a ao máximo e sem arrependimentos.",
    "Seja corajoso e enfrente seus medos, as recompensas são grandes.",
    "Seja a mudança que você deseja ver no mundo.",
    "Aprenda a ouvir e ser guiado por sua intuição.",
    "Encontre o equilíbrio entre trabalho e vida pessoal para uma vida feliz e saudável.",
    "A sorte é apenas uma pequena parte do sucesso, o trabalho duro é a chave.",
    "Não tenha medo de falhar, as falhas são lições valiosas.",
    "Aprenda a perdoar a si mesmo e aos outros, isso libera energia positiva.",
    "Seja gentil consigo mesmo e com os outros, todo mundo está lutando uma batalha.",
    "Acredite em si mesmo e em seu potencial, você pode alcançar grandes coisas.",
    "Aprenda a apreciar a jornada tanto quanto a chegada.",
    "A vida é uma aventura, explore-a e descubra coisas novas.",
    "Não leve a vida tão a sério, ria mais e aproveite o momento presente.",

  ];